services:
  web:
    build:
      context: .
      dockerfile: ./odoo/Dockerfile
      args:
        MAJOR_VERSION: 15
        REVISION_DATE: 20220124
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - odoo-web-data:/var/lib/odoo
    environment:
      - ODOO_LOGGING_JSON=1
      - ODOO_REQUESTS_LOGGING=1
      - ODOO_DATABASE=task1
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "10"
  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "10"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d task1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  odoo-web-data:
  odoo-db-data:
