services:
  web:
    volumes:
      - ./config/odoo.staging.conf:/etc/odoo/odoo.conf
  proxy:
    image: nginx:1.21.5
    restart: always
    volumes:
      - ./config/nginx.staging.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      web:
        condition: service_started
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "10"
    networks:
      default:
      ics:
        aliases:
          - ${NETWORK_ALIAS}

networks:
  default:
  ics:
    external: true
